[book]
title = "Hermes Android Kotlin SDK Book"
authors = ["Aduki Org"]
description = "Comprehensive developer guide and API reference for the high-performance Hermes Android Kotlin SDK."
language = "en"
src = "."

[output.html]
git-repository-url = "https://github.com/adukilabs/hermers-kt"
edit-url-template = "https://github.com/adukilabs/hermers-kt/edit/main/docs/{path}"
site-url = "/hermers-kt/"
default-theme = "rust"
preferred-dark-theme = "coal"
mathjax-support = false

[output.html.fold]
enable = true
level = 1
